# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

app_identifier = "gb.pillsTime"
username = "kosolapovnikitav@gmail.com"

default_platform(:ios)
  lane :testflight_lane do

    # sing code
    cert
    sigh

    # clear data
    clear_derived_data
    xcclean(
        scheme: "Pills",
        workspace: "Pills.xcworkspace"
    )

    # update dependencies
    cocoapods(
         use_bundle_exec: false
    )

    # increment build number
    version = get_version_number(
                     xcodeproj: "Piils.xcodeproj", 
                     target: "Pills"
              )

    build_number = latest_testflight_build_number(
                         version: version,   
                         app_identifier: app_identifier
                    )

    increment_build_number({
      build_number: build_number + 1
    })

    # gym
    build_app(
      scheme: "Pills", #The project's scheme.
      configuration: "Debug", #The configuration to use when building the app. 
      include_symbols: true, #Should the ipa file include symbols?
      include_bitcode: true, #Should the ipa file include bitcode?
      silent: true, #Hide all information that's not necessary while building
    )

    # testFlight
    upload_to_testflight(
      username: username,
      app_identifier: app_identifier
    )

    # commit changes to git

    #versionNumber = get_version_number
    #buildNumber = get_build_number
    #tag = "#{versionNumber}.#{buildNumber}"

    #git_add
    #git_add(path: ["./Podfile.lock", "./Pills.xcodeproj/project.pbxproj", "./PillsTests/Info.plist", "./Pills/Application/Info.plist", "./PillsUITests/Info.plist"])
    #git_commit(path: ["./Podfile.lock", "./Pills.xcodeproj/project.pbxproj", "./PillsTests/Info.plist", "./Pills/Application/Info.plist", "./PillsUITests/Info.plist"], message: "verson up")
    #dd_git_tag(
    # tag: tag
    #)
  end
