# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)
  lane :project do
  # checkout release branch
  # ensure_git_status_clean

    # clear data
    clear_derived_data
    xcclean(
        scheme: "Pills",
        workspace: "Pills.xcworkspace"
    )

    # update a dependencies
    cocoapods(
         use_bundle_exec: false
    )

    # run_tests

    increment_build_number
    #set_info_plist_value(path: "./Pills/Application/Info.plist", key: "CFBundleShortVersionString", value: "2.0")

  build_app(
    scheme: "Pills", #The project's scheme.
    configuration: "Debug", #The configuration to use when building the app. 
    export_method: "development", #Method used to export the archive.
    include_symbols: true, #Should the ipa file include symbols?
    include_bitcode: true, #Should the ipa file include bitcode?
    silent: true, #Hide all information that's not necessary while building
    xcargs: "-allowProvisioningUpdates" #enable Automatically Manage Signing feature
  )

    # commit changes to git

    #versionNumber = get_version_number
    #buildNumber = get_build_number
    #tag = "#{versionNumber}.#{buildNumber}"

    #git_add
    #git_add(path: ["./Podfile.lock", "./Pills.xcodeproj/project.pbxproj", "./PillsTests/Info.plist", "./Pills/Application/Info.plist", "./PillsUITests/Info.plist"])
    #git_commit(path: ["./Podfile.lock", "./Pills.xcodeproj/project.pbxproj", "./PillsTests/Info.plist", "./Pills/Application/Info.plist", "./PillsUITests/Info.plist"], message: "verson up")
    #dd_git_tag(
    # tag: tag
    #)

    upload_to_testflight(
      username: "kosolapovnikitav@gmail.com",
      app_identifier: "gb.pillsTime"
    )
  end

  lane :release do
    sync_code_signing
    disable_automatic_code_signing(path: "Pills.xcodeproj")
    build_app
    enable_automatic_code_signing(path: "Pills.xcodeproj")
    upload_to_testflight
  end
