# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Pills' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'RealmSwift', '10.7.2'
  pod 'FSCalendar', '2.8.2'
  pod 'DropDown', '2.3.13'

  # Pods for Pills

  target 'PillsTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'RealmSwift'
  end

  target 'PillsUITests' do
    # Pods for testing
  end

end
